version: '3.9'

services:
  backend:
    build: ./app
    command: sh ./commands.sh
    volumes:
      - static_volume:/home/app/web/static
      - media_volume:/home/app/web/media
    depends_on:
      - postgres
    expose:
      - 8000

  postgres:
    image: 'postgres'
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=netology
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - ./logs:/var/logs
    restart: unless-stopped

  nginx:
    build: ./nginx
    depends_on:
      - backend
    volumes:
      - static_volume:/home/app/web/static
      - media_volume:/home/app/web/media
    ports:
      - 80:80

volumes:
  postgres_data:
  static_volume:
  media_volume: